NAMASTE_EMAIL: FANCY_CART_ACCT@EMAIL.COM
NAMASTE_PASSWD: SUPER_CRYPTO_PWD

SENDER_GMAIL_ID: SENDER_GMAIL_ID
SENDER_GMAIL_PWD: SENDER_GMAIL_PWD
RECEIVER_GMAIL_ID: RECEIVER_GMAIL_ID

LOCATION: 2
# 1 for Lawrence - 1202 APOLLO WAY, SUNNYVALE, CA, 94085
# 2 for Hollenbeck - 1637 HOLLENBECK AVE, SUNNYVALE, CA, 94087
# 4 for San Jose - 1763 CAPITOL EXPY, SAN JOSE, CA, 95121

OPEN_BROWSER: 1
